version: "3.8"
services:
  backend:
    image: girlathon-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
        - .env.example
    ports:
      - "5001:5001"
    dns:
      -8.8.8.8
    networks:
      - girlathon
  frontend:
    image: girlathon-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env.example
    ports:
      - "5173:5173"
    dns:
      -8.8.8.8
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - backend
    networks:
      - girlathon
  admin:
    image: girlathon-admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    env_file:
      - .env.example
    ports:
      - "3000:3000"
    dns:
      -8.8.8.8
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - girlathon
networks:
    girlathon:


